language: go
go:
  - "1.10.x"
matrix:
  include:
    os:
      - linux
      - osx
    before_install:
      - go get github.com/mpsido/leboncoin-go
      - make install-dev
    install:
      - make dep
    script:
      - make test
